kind: Deployment
apiVersion: apps/v1
metadata:
  name: dpu-management-testv1
  namespace: neo4j
  annotations:
    argocd-image-updater.argoproj.io/image-list: 'management=management:test'
    argocd-image-updater.argoproj.io/nginx.update-strategy: latest
  labels:
    app: dpu-management-testv1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpu-management-testv1
  template:
    metadata:
      labels:
        app: dpu-management-testv1
        role: rolling-update
    spec:
      containers:
        - name: dpu-management-testv1
          image: bakcovn/dpu-management:test
      imagePullSecrets:
        - name: regcred
  strategy:
    type: RollingUpdate 